# configuration file for dotnet-releaser
[msbuild]
project = "BattleManager.sln"
[github]
user = "bunnycou"
repo = "BattleManager"
[nuget]
publish = "false"
[msbuild.properties]
PublishTrimmed = false
