# configuration file for dotnet-releaser
[msbuild]
project = "BattleManager.sln"
[github]
user = "bunnycou"
repo = "BattleManager"
[nuget]
publish = false
[msbuild.properties]
PublishTrimmed = false
# Create zip files only for Windows platforms
[[pack]]
rid = ["win-x64"]
kinds = ["zip"]
# Default targets for Linux/Ubuntu Debian compatible distro with debian and tar packages
[[pack]]
publish = false
rid = ["linux-x64", "linux-arm", "linux-arm64"]
kinds = ["deb", "tar"]
# Default targets for Linux/Redhat compatible distro with rpm and tar packages
[[pack]]
publish = false
rid = ["rhel-x64"]
kinds = ["rpm", "tar"]
# Default targets for macOS, only tar files for this platform
[[pack]]
publish = false
rid = ["osx-x64", "osx-arm64"]
kinds = ["tar"]